#!/bin/bash
set -e

psql --echo-all -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
SELECT datname FROM pg_database
WHERE datistemplate = false;
EOSQL

psql --echo-all -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE ROLE acme_admin NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD '${ACME_ADMIN_PW}';
CREATE ROLE acme_rw    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD '${ACME_RW_PW}';
CREATE ROLE acme_ro    NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN PASSWORD '${ACME_RO_PW}';

CREATE DATABASE acme OWNER acme_admin LC_COLLATE 'en_US.utf8' LC_CTYPE 'en_US.utf8';
REVOKE ALL PRIVILEGES ON DATABASE acme FROM PUBLIC;

GRANT CONNECT ON DATABASE acme TO acme_admin;
GRANT CONNECT ON DATABASE acme TO acme_rw;
GRANT CONNECT ON DATABASE acme TO acme_ro;
EOSQL

psql --echo-all  -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "acme" <<-EOSQL

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT CREATE,USAGE ON SCHEMA public TO acme_admin;
GRANT USAGE ON SCHEMA public TO acme_ro;
GRANT USAGE ON SCHEMA public TO acme_rw;

-- tables
ALTER DEFAULT PRIVILEGES FOR USER acme_admin GRANT ALL ON TABLES TO acme_admin;
ALTER DEFAULT PRIVILEGES FOR USER acme_admin GRANT ALL ON TABLES TO acme_rw;
ALTER DEFAULT PRIVILEGES FOR USER acme_admin GRANT SELECT ON TABLES TO acme_ro;

-- sequences
ALTER DEFAULT PRIVILEGES FOR USER acme_admin GRANT ALL ON SEQUENCES TO acme_admin;
ALTER DEFAULT PRIVILEGES FOR USER acme_admin GRANT ALL ON SEQUENCES TO acme_rw;
ALTER DEFAULT PRIVILEGES FOR USER acme_admin GRANT SELECT ON SEQUENCES TO acme_ro;
EOSQL
