"""profile length

Revision ID: 3b9114fe9d3a
Revises: 4245b2ccf302
Create Date: 2025-10-19 08:53:26.193930

"""

from alembic import op
import sqlalchemy as sa
import acmetk.models.account
import acmetk.models.base
import acmetk.models.order
import acmetk.models.certificate


# revision identifiers, used by Alembic.
revision = "3b9114fe9d3a"
down_revision = "4245b2ccf302"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "profile", existing_type=sa.String(), type_=sa.String(length=32), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "profile", existing_type=sa.String(32), type_=sa.String(), existing_nullable=True)
    # ### end Alembic commands ###
