"""ARI

Revision ID: 4245b2ccf302
Revises: 9a65b93bfa0a
Create Date: 2025-02-05 15:39:15.345649

"""

from alembic import op
import sqlalchemy as sa
import acmetk.models.account
import acmetk.models.base
import acmetk.models.order
import acmetk.models.certificate


# revision identifiers, used by Alembic.
revision = "4245b2ccf302"
down_revision = "9a65b93bfa0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "certificates",
        sa.Column("certid", sa.String(length=64), nullable=True),
    )

    bind = op.get_bind()
    from sqlalchemy import orm, select
    from acmetk.models import Certificate
    from acmetk.util import CertID

    session = orm.Session(bind=bind)

    q = select(Certificate).options().where(Certificate.certid == None)
    print(q)
    m = session.execute(q).all()
    c = []
    for (i,) in m:
        try:
            i.certid = CertID.from_cert(i.cert).identifier
        except:
            i.certid = CertID(b"aaaa", i.cert.serial_number).identifier
        c.append(i)

    session.add_all(c)
    session.commit()

    op.alter_column("certificates", "certid", nullable=False)
    op.create_index(
        op.f("ix_certificates_certid"), "certificates", ["certid"], unique=True
    )
    op.add_column("orders", sa.Column("replaces", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_orders_account_id"), "orders", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_orders_replaces"), "orders", ["replaces"], unique=False)
    op.create_foreign_key(
        op.f("fk_orders_replaces_certificates"),
        "orders",
        "certificates",
        ["replaces"],
        ["certid"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_orders_replaces_certificates"), "orders", type_="foreignkey"
    )
    op.drop_index(op.f("ix_orders_replaces"), table_name="orders")
    op.drop_index(op.f("ix_orders_account_id"), table_name="orders")
    op.drop_column("orders", "replaces")
    op.drop_index(op.f("ix_certificates_certid"), table_name="certificates")
    op.drop_column("certificates", "certid")
    # ### end Alembic commands ###
