"""Order has profiles field - draft-aaron-acme-profiles-00

Revision ID: 9a65b93bfa0a
Revises: 09326e75277d
Create Date: 2025-01-27 12:12:30.921756

"""

from alembic import op
import sqlalchemy as sa
import acmetk.models.account
import acmetk.models.base
import acmetk.models.order
import acmetk.models.certificate


# revision identifiers, used by Alembic.
revision = "9a65b93bfa0a"
down_revision = "24004ca7a5ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("profile", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "profile")
    # ### end Alembic commands ###
